# Integration test for the following packages:
# https://github.com/scikit-hep/awkward/blob/main/.github/workflows/test.yml
# https://github.com/dask-contrib/dask-awkward/blob/main/.github/workflows/pypi-tests.yml
# https://github.com/scikit-hep/uproot5/blob/main/.github/workflows/build-test.yml
# https://github.com/scikit-hep/coffea/blob/master/.github/workflows/ci.yml
# https://github.com/scikit-hep/vector/blob/main/.github/workflows/ci.yml

name: Integration Tests

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'bash -l {0}' || '' }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java-version: [17]
        java-distribution: ["corretto"]
        python-version: ["3.9", "3.13"]
        dask-client: ["with", "without"]

    name: Test (${{ matrix.os }}) - 🐍 ${{ matrix.python-version }}, JDK${{ matrix.java-version }}, ${{ matrix.dask-client }} dask

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: JDK ${{ matrix.java-distribution }}/${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync env
        run: |
          git lfs install --skip-smudge
          uv sync

      - name: Clone scikit-hep/awkward
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/awkward
          path: repo-awkward
          submodules: true
          ref: "main"

      - name: Clone dask-contrib/dask-awkward
        uses: actions/checkout@v4
        with:
          repository: dask-contrib/dask-awkward
          path: repo-dask-awkward
          ref: "main"
          fetch-depth: 0
          lfs: true

      - name: Clone scikit-hep/uproot5
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/uproot5
          path: repo-uproot5
          ref: "main"

      - name: Clone scikit-hep/vector
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/vector
          path: repo-vector
          ref: "main"

      - name: Clone scikit-hep/coffea
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/coffea
          path: repo-coffea
          ref: "master"
          fetch-depth: 0

      - name: Build awkward-cpp
        run: |
          cd repo-awkward
          pipx run nox -s prepare -- --headers --signatures --tests
          uv pip install -vv ./awkward-cpp
          cd ..

      - name: Build awkward
        run: |
          cd repo-awkward
          uv pip install '.[test]'
          uv pip install -r requirements-test-full.txt
          cd ..

      - name: Build dask-awkward
        run: |
          cd repo-dask-awkward
          uv pip install '.[complete,test]'
          cd ..

      - name: Build uproot
        run: |
          cd repo-uproot5
          uv pip install -e. --group=dev
          cd ..

      - name: Build vector
        run: |
          cd repo-vector
          uv pip install '.[dev]'
          cd ..

      - name: Build coffea
        run: |
          cd repo-coffea
          uv pip install '.[dev,dask]'
          cd ..

      - name: Add xdist
        run: uv pip install pytest-xdist

      - name: Show all versions
        run: uv pip list

      - name: Test scikit-hep/awkward
        id: test-awkward
        run: |
          if uv run pytest -vv -rs repo-awkward/tests -n 4; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test dask-contrib/dask-awkward
        id: test-dask-awkward
        run: |
          if uv run pytest -vv -rs repo-dask-awkward/tests -n 1; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/uproot5
        id: test-uproot
        run: |
          cd repo-uproot5/
          if uv run --project .. pytest -vv -rs tests --reruns 10 --reruns-delay 30 --only-rerun "(?i)http|ssl|timeout|expired|connection|socket"; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test dask-contrib/vector
        id: test-vector
        run: |
          cd repo-vector/
          if uv run --project .. pytest -vv -rs tests --ignore tests/test_notebooks.py -n 4; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/coffea, (${{ matrix.dask-client }} dask Client - run in parallel)
        id: test-coffea
        run: |
          cd repo-coffea/
          if uv run --project .. pytest -vv -rs tests --deselect=test_taskvine -m "${{ matrix.dask-client == 'without' && 'not ' || '' }}dask_client" -n 4; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Summary
        run: |
          echo "# Tests Summary" >> $GITHUB_STEP_SUMMARY
          echo "Awkward ${{ steps.test-awkward.outputs.success && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "Dask-Awkward ${{ steps.test-dask-awkward.outputs.success && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "Uproot ${{ steps.test-uproot.outputs.success && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "Vector ${{ steps.test-vector.outputs.success && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "Coffea ${{ steps.test-coffea.outputs.success && '✅ Passed' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          # Ignore the output outcome of dask-awkward since it's flaky
          ${{ steps.test-awkward.outputs.success && steps.test-uproot.outputs.success && steps.test-vector.outputs.success && steps.test-coffea.outputs.success && 'true' || 'false' }}
